### ISSUE TITLE
error in build

### ISSUE THREAD

**Issue by Un1Lee** [LimHyungTae/quatro-cpp-fpfh#2]
I can't understand ' Quatro is included in include/teaser/registration.h '. 
When I after install Teaser++, I can run its example, then I get quatro-cpp-fpfh like Teaser++'s example.
But it report error: ‘QUATRO’ is not a member of ‘teaser::RobustRegistrationSolver::ROTATION_ESTIMATION_ALGORITHM’.
Is there any step I miss? Can you give more details about how to build?
Thank you very much!

**Comment by LimHyungTae** [comment]
Hello, thank you for interest. Unfortunately, Quatro is not merged yet in TEASER++ (check the PR. PR is not accepted yet :( )

**Comment by Un1Lee** [comment]
> Hello, thank you for interest. Unfortunately, Quatro is not merged yet in TEASER++ (check the PR. PR is not accepted yet :( )

Thank you!
